<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Moroccan cities + zones
    |--------------------------------------------------------------------------
    | Format:
    | 'zone_or_place' => 'Main City'
    |
    | Used to detect a city even when the CV contains a district / industrial zone.
    */

    'city_aliases' => [
        // Casablanca
        'casablanca' => 'Casablanca',
        'casa' => 'Casablanca',
        'dar el beida' => 'Casablanca',
        'dar el baida' => 'Casablanca',
        'maarif' => 'Casablanca',
        'maârif' => 'Casablanca',
        'ain sebaa' => 'Casablanca',
        'aïn sebaa' => 'Casablanca',
        'ain chok' => 'Casablanca',
        'sidi maarouf' => 'Casablanca',
        'sidi maârouf' => 'Casablanca',
        'hay hassani' => 'Casablanca',
        'hay mohammedi' => 'Casablanca',
        'anfa' => 'Casablanca',
        'bourgogne' => 'Casablanca',
        'oulfa' => 'Casablanca',
        'derb sultan' => 'Casablanca',
        'alfida' => 'Casablanca',
        'hay el farah' => 'Casablanca',
        'hay moulay rachid' => 'Casablanca',
        'moulay rachid' => 'Casablanca',
        'bernoussi' => 'Casablanca',
        'sidi bernoussi' => 'Casablanca',
        'roches noires' => 'Casablanca',
        'belvedere' => 'Casablanca',
        'belvédère' => 'Casablanca',
        'la villette' => 'Casablanca',
        'californie' => 'Casablanca',
        'bouskoura' => 'Casablanca',
        'nouaceur' => 'Casablanca',
        'dar bouazza' => 'Casablanca',
        'ain diab' => 'Casablanca',
        'aïn diab' => 'Casablanca',
        'sidi moumen' => 'Casablanca',
        'tit mellil' => 'Casablanca',
        'mediouna' => 'Casablanca',
        'médiouna' => 'Casablanca',
        'ain harrouda' => 'Casablanca',
        'aïn harrouda' => 'Casablanca',
        'mohammedia' => 'Casablanca',
        'berrechid' => 'Casablanca',
        'had soualem' => 'Casablanca',
        'deroua' => 'Casablanca',
        'lahraouyine' => 'Casablanca',
        'zenata' => 'Casablanca',
        'zone industrielle ain sebaa' => 'Casablanca',
        'zone industrielle sidi bernoussi' => 'Casablanca',
        'zone industrielle moulay rachid' => 'Casablanca',
        'zone industrielle bouskoura' => 'Casablanca',
        'zone industrielle nouaceur' => 'Casablanca',

        // Rabat / Salé / Témara
        'rabat' => 'Rabat',
        'agdal' => 'Rabat',
        'hay riad' => 'Rabat',
        'hay riyad' => 'Rabat',
        'souissi' => 'Rabat',
        'akkari' => 'Rabat',
        'youssoufia rabat' => 'Rabat',
        'océan' => 'Rabat',
        'ocean' => 'Rabat',
        'hassan rabat' => 'Rabat',
        'sale' => 'Rabat',
        'salé' => 'Rabat',
        'tabriquet' => 'Rabat',
        'bettana' => 'Rabat',
        'hay salam sale' => 'Rabat',
        'bouknadel' => 'Rabat',
        'temara' => 'Rabat',
        'témara' => 'Rabat',
        'skhirat' => 'Rabat',
        'harhoura' => 'Rabat',
        'ain atiq' => 'Rabat',
        'aïn atiq' => 'Rabat',
        'sidi yahya zaer' => 'Rabat',
        'technopolis' => 'Rabat',
        'zone industrielle temara' => 'Rabat',
        'zone industrielle ain atiq' => 'Rabat',

        // Tanger / Tétouan
        'tanger' => 'Tanger',
        'tangier' => 'Tanger',
        'tanger med' => 'Tanger',
        'tanger free zone' => 'Tanger',
        'tfz' => 'Tanger',
        'gueznaya' => 'Tanger',
        'gzenaya' => 'Tanger',
        'malabata' => 'Tanger',
        'boukhalef' => 'Tanger',
        'asilah' => 'Tanger',
        'ksar sghir' => 'Tanger',
        'tetouan' => 'Tétouan',
        'tétouan' => 'Tétouan',
        'martil' => 'Tétouan',
        'mdiq' => 'Tétouan',
        'm diq' => 'Tétouan',
        'fnideq' => 'Tétouan',
        'rincon' => 'Tétouan',
        'chefchaouen' => 'Chefchaouen',
        'larache' => 'Larache',
        'ksar el kebir' => 'Larache',
        'kser el kebir' => 'Larache',

        // Fès / Meknès
        'fes' => 'Fès',
        'fès' => 'Fès',
        'fez' => 'Fès',
        'saiss' => 'Fès',
        'sais' => 'Fès',
        'ain chkef' => 'Fès',
        'aïn chkef' => 'Fès',
        'narjiss' => 'Fès',
        'oued fes' => 'Fès',
        'zone industrielle dokkarat' => 'Fès',
        'meknes' => 'Meknès',
        'meknès' => 'Meknès',
        'hamria' => 'Meknès',
        'toulal' => 'Meknès',
        'sidi bouzekri' => 'Meknès',
        'el hajeb' => 'Meknès',
        'ifrane' => 'Ifrane',
        'azrou' => 'Ifrane',

        // Marrakech / Safi
        'marrakech' => 'Marrakech',
        'marrakesh' => 'Marrakech',
        'gueliz' => 'Marrakech',
        'guéliz' => 'Marrakech',
        'hivernage' => 'Marrakech',
        'mhamid marrakech' => 'Marrakech',
        'sidi ghanem' => 'Marrakech',
        'massira marrakech' => 'Marrakech',
        'targa' => 'Marrakech',
        'tamansourt' => 'Marrakech',
        'ait ourir' => 'Marrakech',
        'safi' => 'Safi',
        'youssoufia' => 'Safi',
        'el kelaa des sraghna' => 'Marrakech',
        'essaouira' => 'Essaouira',

        // Agadir / Souss
        'agadir' => 'Agadir',
        'inzegane' => 'Agadir',
        'inezgane' => 'Agadir',
        'ait melloul' => 'Agadir',
        'aït melloul' => 'Agadir',
        'dcheira' => 'Agadir',
        'dcheira el jihadia' => 'Agadir',
        'tikiouine' => 'Agadir',
        'drarga' => 'Agadir',
        'anaza' => 'Agadir',
        'taroudant' => 'Taroudant',
        'ouled teima' => 'Taroudant',
        'oulad teima' => 'Taroudant',
        'tiznit' => 'Tiznit',
        'sidi ifni' => 'Sidi Ifni',

        // Oriental
        'oujda' => 'Oujda',
        'berkane' => 'Berkane',
        'nador' => 'Nador',
        'selouane' => 'Nador',
        'zaio' => 'Nador',
        'driouch' => 'Nador',
        'taourirt' => 'Taourirt',
        'jerada' => 'Jerada',
        'figuig' => 'Figuig',
        'guercif' => 'Guercif',

        // Béni Mellal / Khouribga
        'beni mellal' => 'Béni Mellal',
        'béni mellal' => 'Béni Mellal',
        'fquih ben salah' => 'Béni Mellal',
        'kasba tadla' => 'Béni Mellal',
        'azilal' => 'Azilal',
        'khouribga' => 'Khouribga',
        'oued zem' => 'Khouribga',
        'boujniba' => 'Khouribga',
        'bejaad' => 'Khouribga',
        'bejaâd' => 'Khouribga',

        // El Jadida / Settat
        'el jadida' => 'El Jadida',
        'jadida' => 'El Jadida',
        'jorf lasfar' => 'El Jadida',
        'azemmour' => 'El Jadida',
        'sidi bennour' => 'El Jadida',
        'settat' => 'Settat',
        'ben ahmed' => 'Settat',
        'benslimane' => 'Benslimane',
        'bouznika' => 'Benslimane',

        // South
        'laayoune' => 'Laâyoune',
        'laâyoune' => 'Laâyoune',
        'layoune' => 'Laâyoune',
        'dakhla' => 'Dakhla',
        'guelmim' => 'Guelmim',
        'tan tan' => 'Tan-Tan',
        'tan-tan' => 'Tan-Tan',
        'assa' => 'Assa-Zag',
        'zag' => 'Assa-Zag',
        'smara' => 'Smara',
        'boujdour' => 'Boujdour',
        'tarfaya' => 'Tarfaya',

        // Other
        'taza' => 'Taza',
        'al hoceima' => 'Al Hoceima',
        'alhoceima' => 'Al Hoceima',
        'errachidia' => 'Errachidia',
        'errachidia' => 'Errachidia',
        'midelt' => 'Midelt',
        'tinghir' => 'Tinghir',
        'ouarzazate' => 'Ouarzazate',
        'zagora' => 'Zagora',
        'khemisset' => 'Khémisset',
        'khémisset' => 'Khémisset',
        'sidi kacem' => 'Sidi Kacem',
        'sidi slimane' => 'Sidi Slimane',
        'souk el arbaa' => 'Kénitra',
        'souk larbaa' => 'Kénitra',
    ],

    /*
    |--------------------------------------------------------------------------
    | Main city list
    |--------------------------------------------------------------------------
    */

    'cities' => [
        'Casablanca', 'Rabat', 'Salé', 'Témara', 'Kénitra', 'Mohammedia',
        'Bouskoura', 'Nouaceur', 'Berrechid', 'Settat', 'El Jadida', 'Safi',
        'Marrakech', 'Agadir', 'Inezgane', 'Ait Melloul', 'Essaouira', 'Taroudant',
        'Fès', 'Meknès', 'Taza', 'Oujda', 'Nador', 'Berkane', 'Al Hoceima',
        'Tétouan', 'Tanger', 'Larache', 'Chefchaouen', 'Errachidia', 'Ouarzazate',
        'Béni Mellal', 'Khouribga', 'Laâyoune', 'Dakhla', 'Guelmim', 'Tan-Tan',
        'Zagora', 'Midelt', 'Azilal', 'Tiznit', 'Sidi Ifni', 'Taourirt',
        'Jerada', 'Guercif', 'Figuig', 'Ifrane', 'Youssoufia', 'Benslimane',
        'Bouznika', 'Sidi Bennour', 'Sidi Kacem', 'Sidi Slimane',
    ],

    /*
    |--------------------------------------------------------------------------
    | Moroccan / Arabic / French first names
    |--------------------------------------------------------------------------
    | Used to score human-name candidates.
    */

    'first_names' => [
        // Male common
        'mohamed', 'mohammed', 'mohammad', 'muhammad', 'mohamad', 'mohammede',
        'ahmed', 'hamza', 'youssef', 'yusuf', 'yassine', 'yassin', 'yasin',
        'ayoub', 'anas', 'amine', 'amin', 'omar', 'oumar', 'ali', 'hassan',
        'houssam', 'houssain', 'houssaine', 'houssein', 'hussein', 'mouad',
        'moad', 'moaad', 'mehdi', 'mahdi', 'zakaria', 'zakariya', 'zackaria',
        'abderrahim', 'abdelrahim', 'abdelhak', 'abdelhaq', 'abdelilah',
        'abdellah', 'abdallah', 'abdelali', 'abdelaziz', 'abdelkader',
        'abdelkarim', 'abdelkrim', 'abdelmajid', 'abdelouahed', 'abdelwahab',
        'abderrahmane', 'abderrahman', 'abdelmounim', 'abdelmonim',
        'mustapha', 'mostafa', 'moustapha', 'mustafa', 'khalid', 'khaled',
        'rachid', 'rashid', 'said', 'saïd', 'saad', 'soufiane', 'sofiane',
        'soufyan', 'sofyan', 'reda', 'rida', 'ridha', 'brahim', 'ibrahim',
        'ismail', 'ismael', 'ismaïl', 'othmane', 'othman', 'oussama', 'osama',
        'ilyas', 'ilyass', 'ilias', 'elias', 'anas', 'adnane', 'adnan',
        'bilal', 'badr', 'badre', 'badrddine', 'badr eddine', 'ayman',
        'aymane', 'imad', 'imade', 'nabil', 'nabyl', 'jalal', 'jamal',
        'kamal', 'karim', 'mounir', 'munir', 'mounir', 'noureddine',
        'noureddin', 'noureddine', 'salah', 'salahddine', 'salah eddine',
        'taha', 'tariq', 'tarik', 'walid', 'walide', 'wail', 'wael',
        'anas', 'anas', 'driss', 'idriss', 'ayoub', 'issam', 'samir',
        'sami', 'mohssine', 'mohcine', 'mouhcine', 'mouhsine', 'hicham',
        'hisham', 'younes', 'yunes', 'youness', 'anas', 'hatim', 'hatem',
        'ad il', 'adil', 'abdo', 'abdou', 'hamid', 'lahcen', 'lahssan',
        'larbi', 'el arbi', 'reda', 'mehdi', 'fouad', 'fuad', 'mohsin',
        'mohcine', 'anas', 'aziz', 'hafid', 'hafid', 'simo', 'simohamed',
        'anas', 'mourad', 'morad', 'mourade', 'mahmoud', 'mahmud', 'farid',
        'faycal', 'faisal', 'faysal', 'saber', 'sabre', 'yahia', 'yahya',
        'yahyaa', 'nizar', 'anas', 'marouane', 'marwane', 'marwan',
        'salmane', 'salman', 'anas', 'rafik', 'rafiq', 'hamid', 'habib',
        'anis', 'anes', 'samih', 'samih', 'safouane', 'safwan', 'safouan',
        'achraf', 'ashraf', 'anas', 'chouaib', 'choaib', 'chuayb',
        'mohamed amine', 'mohammed amine', 'amine mohamed', 'mohamed ali',
        'mohamed yassine', 'mohamed ayoub', 'mohamed reda', 'mohamed mehdi',

        // Female common
        'fatima', 'fatma', 'fatiha', 'zahra', 'zohra', 'fatima zahra',
        'fatimazahra', 'khadija', 'khadidja', 'kadija', 'aicha', 'aïcha',
        'aisha', 'aycha', 'maryam', 'meryem', 'mariam', 'mariam', 'salma',
        'salmā', 'asmaa', 'asma', 'asfaa', 'hajar', 'hajer', 'ikram',
        'imane', 'iman', 'jihane', 'jihan', 'hanane', 'hanan', 'ibtissam',
        'ibtisam', 'sanaa', 'sanae', 'sana', 'sara', 'sarah', 'souad',
        'suad', 'zineb', 'zainab', 'zeineb', 'nada', 'nadia', 'nawal',
        'nawal', 'amal', 'amal', 'lamia', 'lamiae', 'lamyae', 'lamya',
        'oumaima', 'oum aima', 'oumayma', 'aya', 'ayat', 'doha', 'douaa',
        'doua', 'ikhlas', 'wiam', 'wissal', 'widad', 'ghizlane', 'ghita',
        'ibtissame', 'hafsa', 'hafsah', 'siham', 'sihem', 'samira', 'samia',
        'saida', 'saïda', 'soukaina', 'soukaïna', 'soukayna', 'sukaina',
        'chaimae', 'chaimaa', 'shaymae', 'salima', 'halima', 'karima',
        'latifa', 'loubna', 'lubna', 'hind', 'houda', 'hoda', 'hajar',
        'mouna', 'muna', 'mounia', 'munia', 'ilham', 'elhame', 'ilhame',
        'soraya', 'souraya', 'touria', 'nadège', 'nadia', 'najwa',
        'najoua', 'nouhaila', 'nohayla', 'nour', 'nour el houda',
        'nourhane', 'nourhan', 'yasmine', 'yasmina', 'yasmin', 'yasemine',
        'rim', 'reem', 'rime', 'rania', 'ranya', 'rabia', 'rabiae',
        'rajaa', 'rajae', 'raja', 'manal', 'marwa', 'maroua', 'marwa',
        'malak', 'meriem', 'meryam', 'sabrina', 'sabri', 'safae', 'safa',
        'safaa', 'kaoutar', 'kawtar', 'khaoula', 'kawla', 'houda',
        'hasna', 'hasnae', 'hassna', 'bouchra', 'bushra', 'bouchra',
        'firdaws', 'firdaous', 'ferdaous', 'yasmina', 'amina', 'amina',
        'amima', 'amina zahra', 'basma', 'asmae', 'ilham', 'maha',
        'nihad', 'nouria', 'ouidad', 'salsabil', 'wissam', 'zaina',
        'zahia', 'zoubida', 'zineb', 'safia', 'safiya',

        // French / international common
        'alexandre', 'antoine', 'arthur', 'benjamin', 'cedric', 'cédric',
        'christophe', 'david', 'eric', 'éric', 'franck', 'francois',
        'françois', 'guillaume', 'julien', 'kevin', 'kévin', 'laurent',
        'lucas', 'marc', 'mathieu', 'maxime', 'nicolas', 'olivier',
        'paul', 'pierre', 'quentin', 'romain', 'sebastien', 'sébastien',
        'stephane', 'stéphane', 'thomas', 'victor', 'vincent',
        'alice', 'amelie', 'amélie', 'anaïs', 'anais', 'camille',
        'charlotte', 'claire', 'elodie', 'élodie', 'emma', 'ines',
        'inès', 'julie', 'laura', 'lea', 'léa', 'lina', 'lucie',
        'manon', 'marie', 'nora', 'sophie', 'valerie', 'valérie',
    ],

    /*
    |--------------------------------------------------------------------------
    | Moroccan family names
    |--------------------------------------------------------------------------
    | Used to score candidate names.
    */

    'last_names' => [
        'alami', 'el alami', 'benjelloun', 'benjelloune', 'bennani', 'bennouna',
        'tazi', 'tazy', 'fassi', 'el fassi', 'idrissi', 'el idrissi',
        'alaoui', 'el alaoui', 'cherkaoui', 'charkaoui', 'bennis', 'berrada',
        'barrada', 'sefrioui', 'sqalli', 'skalli', 'lahlou', 'lazrak',
        'lazaar', 'lamrani', 'lamrini', 'lamghari', 'el amrani', 'amrani',
        'ait taleb', 'ait', 'taleb', 'el khattabi', 'khattabi', 'boulahya',
        'boulahya', 'bouziane', 'bouzid', 'boussaid', 'bousfiha', 'bensouda',
        'benslimane', 'bensalem', 'bensaid', 'bensaïd', 'bensghir',
        'benomar', 'ben omar', 'benali', 'ben ali', 'bennasser',
        'bennasr', 'benmoussa', 'ben moussa', 'benbrahim', 'ben brahim',
        'benchekroun', 'benchakroun', 'benkirane', 'benkiran', 'benyahia',
        'ben yahia', 'benyoussef', 'ben youssef', 'benaissa', 'ben aissa',
        'benaïssa', 'bennour', 'bennani', 'belhaj', 'bel haj', 'belkadi',
        'belcadi', 'belkhayat', 'belkacem', 'bel kacem', 'belarbi',
        'bel arbi', 'belhadj', 'belmaati', 'bel maati', 'belghiti',
        'belghazi', 'belmokhtar', 'bel mokhtar', 'belabbes', 'bel abbes',
        'el harrak', 'harrak', 'el khalfi', 'khalfi', 'el bouzidi',
        'bouzidi', 'el ouardi', 'ouardi', 'el mansouri', 'mansouri',
        'el hamdaoui', 'hamdaoui', 'el kadiri', 'kadiri', 'el azzouzi',
        'azzouzi', 'el moudden', 'moudden', 'el bani', 'bani',
        'el ghrari', 'ghrari', 'el hafidi', 'hafidi', 'el hachimi',
        'hachimi', 'el housni', 'housni', 'el idrissi', 'idrissi',
        'el malki', 'malki', 'el mehdi', 'mehdi', 'el mokhtari',
        'mokhtari', 'el omari', 'omari', 'el qadi', 'qadi',
        'el rhaffouli', 'el rhazouani', 'rhazouani', 'el yahyaoui',
        'yahyaoui', 'el yaacoubi', 'yaacoubi', 'el yousfi', 'yousfi',
        'el youssefi', 'youssefi', 'el habti', 'habti', 'el assri',
        'assri', 'el alami', 'alami', 'el filali', 'filali',
        'el khadir', 'khadir', 'el moujahid', 'moujahid', 'el moumni',
        'moumni', 'el ouazzani', 'ouazzani', 'el ouafi', 'ouafi',
        'el fakir', 'fakir', 'el fadili', 'fadili', 'el ghadraoui',
        'ghadraoui', 'el haddadi', 'haddadi', 'el haddad', 'haddad',
        'el harradi', 'harradi', 'el hassani', 'hassani', 'el hilali',
        'hilali', 'el khayari', 'khayari', 'el khouya', 'khouya',
        'el maati', 'maati', 'el madani', 'madani', 'el mahdi',
        'el mejdoub', 'mejdoub', 'el mrabet', 'mrabet', 'el ouali',
        'ouali', 'el ouazzani', 'ouazzani', 'el oumari', 'oumari',
        'el oumri', 'oumri', 'el qassimi', 'qassimi', 'el rhazi',
        'rhazi', 'el rifi', 'rifi', 'el sayeh', 'sayeh', 'el yamani',
        'yamani', 'el azhari', 'azhari',

        'saoud', 'saidi', 'said', 'saadi', 'sadiqi', 'saddiki', 'seddiki',
        'sabri', 'safri', 'sahraoui', 'sahraouy', 'sanhaji', 'senhaji',
        'sbai', 'sebbai', 'sebbane', 'semlali', 'serhani', 'serghini',
        'skiredj', 'slimani', 'slim', 'souhaili', 'soussi', 'sriti',
        'tahiri', 'tahri', 'talbi', 'tamim', 'tber', 'tijani',
        'trabelsi', 'wahbi', 'wahb', 'wakrim', 'yazidi', 'zaidi',
        'zahraoui', 'zahir', 'zaki', 'zeggaf', 'zerouali', 'zeroual',
        'ziadi', 'ziani', 'zniber', 'zouaoui', 'zouhair', 'zouini',
        'zriouil', 'rahmani', 'rahmouni', 'rami', 'ramdani', 'raji',
        'raki', 'rguig', 'rharrabti', 'rhani', 'riyahi', 'rouissi',
        'rouijel', 'sabbah', 'saber', 'amghar', 'azizi', 'aziz',
        'achour', 'achaoui', 'ait hammou', 'ait laarbi', 'ait mbarek',
        'ait said', 'ait ssi', 'akkaoui', 'alaoui', 'allali', 'amari',
        'amellal', 'amhaouch', 'amimi', 'ammari', 'amzazi', 'arabi',
        'arbaoui', 'asri', 'assi', 'attari', 'azami', 'azemmouri',
        'aziz', 'azizian', 'baalla', 'badaoui', 'badri', 'baghdadi',
        'bahri', 'bakkali', 'bakri', 'balafrej', 'bali', 'baraka',
        'baroudi', 'bassir', 'bazzi', 'bejjaji', 'bejjani', 'bekkaoui',
        'belfakir', 'belhadj', 'belhaj', 'belhouari', 'bellahcen',
        'bellamine', 'belmahi', 'belouafi', 'benabdallah', 'benabdeljalil',
        'benaddi', 'benaich', 'benamar', 'benazzi', 'bencheikh',
        'bendaoud', 'bendahmane', 'bendir', 'bendou', 'benhaddou',
        'benhammou', 'benhima', 'benjilali', 'benkaddour', 'benkhaled',
        'benlahcen', 'benmessaoud', 'benomar', 'benrabah', 'bensalah',
        'bensari', 'bensassi', 'bentahar', 'bentayeb', 'bentoumi',
        'berkane', 'berkani', 'berkoun', 'berrada', 'berrehail',
        'bihi', 'bikri', 'boughaba', 'bouazza', 'bouchaib', 'bouchentouf',
        'boucherit', 'bouchra', 'boudali', 'boudiaf', 'boudlal',
        'bouferra', 'bougadir', 'bouhaddi', 'bouhaloua', 'bouhlal',
        'boujida', 'boujraf', 'boukari', 'boukhari', 'boukir',
        'boulahcen', 'boulahya', 'boulifa', 'boumaaz', 'boumahdi',
        'boumalk', 'boumediene', 'bounou', 'bounouar', 'bourass',
        'bourhim', 'bouslimani', 'boussetta', 'boutahar', 'boutaleb',
        'boutayeb', 'boutouil', 'bouyakhlef', 'chafik', 'chafiki',
        'chakir', 'chaouki', 'charaf', 'chbani', 'chebbak', 'chebli',
        'chekroun', 'cherif', 'cherkaoui', 'chihab', 'chraibi',
        'daoudi', 'dahmani', 'dahbi', 'drissi', 'driouich', 'el alami',
        'el amraoui', 'el ansari', 'el arabi', 'el bachiri',
        'el baghdadi', 'el bakkali', 'el bari', 'el bouhali',
        'el boukhari', 'el brahimi', 'el fakiri', 'el fathi',
        'el ghazali', 'el ghazi', 'el ghazioui', 'el haddouchi',
        'el haloui', 'el hamidi', 'el harchaoui', 'el harouchi',
        'el hassouni', 'el hiani', 'el houri', 'el jadidi',
        'el jarmouni', 'el karimi', 'el khadiri', 'el khal',
        'el khattari', 'el khoulati', 'el kouch', 'el kouri',
        'el maazouzi', 'el maliki', 'el mansouri', 'el marzouki',
        'el maslouhi', 'el messaoudi', 'el mhouti', 'el moussaoui',
        'el mrini', 'el ouadghiri', 'el ouali', 'el qasmi',
        'el rami', 'el rhazi', 'el sebbahi', 'el yamani',
        'el yazidi', 'el youbi', 'el yousfi', 'ennaciri',
        'ennaji', 'essadiqi', 'essalhi', 'fahmi', 'fahssi',
        'faraji', 'fathi', 'fennich', 'ferhane', 'ghazali',
        'ghazi', 'ghilani', 'ghoulam', 'guedira', 'guerrouj',
        'hachlaf', 'hachmi', 'haddad', 'haddi', 'hafidi',
        'hajji', 'halimi', 'hamdani', 'hamdouchi', 'hammani',
        'hammi', 'hamzaoui', 'harakat', 'hariri', 'harradi',
        'harrak', 'hassani', 'hassouni', 'hilali', 'jaafari',
        'jabbour', 'jabri', 'jabrane', 'jadidi', 'jafri',
        'jellal', 'jellouli', 'jilali', 'kabbaj', 'kabili',
        'kadiri', 'kairouani', 'karimi', 'karmouni', 'kassimi',
        'kettani', 'khalfi', 'khalil', 'khalis', 'khalloufi',
        'khannoussi', 'kharchich', 'kharrat', 'khatib', 'khattabi',
        'khiat', 'khiyati', 'khouya', 'khyari', 'koumya',
        'lahlou', 'lahmidi', 'lakhdar', 'lamhamdi', 'lamrini',
        'laoudi', 'laouina', 'lazaar', 'lazrak', 'mabrouk',
        'madi', 'mahmoudi', 'majdoubi', 'makhfi', 'maliki',
        'malki', 'mamdouh', 'mansouri', 'marouane', 'marzouki',
        'masmoudi', 'messaoudi', 'meziane', 'mjid', 'mokhtari',
        'morchid', 'mouhoub', 'moujahid', 'moulay', 'moussaoui',
        'naimi', 'najib', 'naji', 'nassiri', 'nfaoui',
        'ouahbi', 'ouali', 'ouazzani', 'oubaha', 'oubella',
        'ouchen', 'ouhadi', 'ouhmid', 'oukili', 'oulad',
        'oumghar', 'ourahou', 'oussama', 'qadiri', 'qorchi',
        'rahal', 'rahhali', 'rahmouni', 'raiss', 'rami',
        'ramzi', 'rassam', 'rguibi', 'rhafiri', 'rhazi',
        'rhouma', 'saadani', 'sadiqi', 'sahli', 'sahnoun',
        'sahraoui', 'sakkali', 'salhi', 'samadi', 'sbai',
        'sebbari', 'sefrioui', 'selmi', 'semghouli', 'serghini',
        'skalli', 'slassi', 'smires', 'souab', 'souhail',
        'taibi', 'tair', 'tajeddine', 'tazi', 'touhami',
        'wakrim', 'yachou', 'yagoubi', 'yahiaoui', 'yaici',
        'zaitouni', 'zaoui', 'zerhouni', 'ziani', 'zouak',
    ],

    /*
    |--------------------------------------------------------------------------
    | Job titles
    |--------------------------------------------------------------------------
    */

    'titles' => [
        // Douane / Transit / Import Export
        'Déclarant en Douane', 'Aide Déclarant en Douane', 'Responsable Douane',
        'Agent de Dédouanement', 'Agent de Transit', 'Assistant Transit',
        'Transitaire', 'Agent Import Export', 'Assistant Import Export',
        'Coordinateur Import Export', 'Chargé Import Export',
        'Responsable Import Export', 'Agent Maritime', 'Agent Consignation',
        'Agent Freight Forwarding', 'Agent Transport International',

        // Logistique / Stock
        'Assistant Logistique', 'Agent Logistique', 'Responsable Logistique',
        'Coordinateur Logistique', 'Gestionnaire de Stock', 'Magasinier',
        'Chef Magasinier', 'Préparateur de Commande', 'Cariste',
        'Responsable Entrepôt', 'Agent d’Expédition', 'Agent de Réception',
        'Contrôleur Réception', 'Agent Quai', 'Dispatcher', 'Approvisionneur',
        'Gestionnaire Approvisionnement', 'Supply Chain Assistant',
        'Supply Chain Manager', 'Planificateur Logistique',

        // Industrie / Maintenance
        'Technicien', 'Technicien de Maintenance', 'Technicien Maintenance Industrielle',
        'Technicien Électricité Industrielle', 'Technicien Électromécanique',
        'Électromécanicien', 'Électricien Industriel', 'Mécanicien Industriel',
        'Technicien Production', 'Opérateur de Production',
        'Agent de Production', 'Chef d’Équipe Production',
        'Responsable Production', 'Technicien Méthodes',
        'Technicien Process', 'Technicien Qualité', 'Contrôleur Qualité',
        'Responsable Qualité', 'Animateur Qualité',
        'HSE Officer', 'Technicien HSE', 'Responsable HSE',

        // IT
        'Technicien Informatique', 'Technicien Support', 'Technicien Réseau',
        'Administrateur Réseau', 'Administrateur Système',
        'Développeur Web', 'Développeur Full Stack',
        'Développeur Frontend', 'Développeur Backend',
        'Ingénieur Informatique', 'Data Analyst', 'Data Scientist',
        'Web Designer', 'Graphic Designer', 'Infographiste',

        // Admin / Finance / RH
        'Assistant Administratif', 'Assistante Administrative',
        'Assistant de Direction', 'Office Manager',
        'Agent Administratif', 'Agent de Saisie',
        'Opérateur de Saisie', 'Comptable', 'Aide Comptable',
        'Chef Comptable', 'Contrôleur de Gestion',
        'Assistant Finance', 'Responsable Administratif et Financier',
        'Assistant RH', 'Gestionnaire RH', 'Gestionnaire Paie',
        'Chargé de Recrutement', 'Responsable RH',
        'Chargé Administration du Personnel',

        // Commercial / Client
        'Commercial', 'Commercial Terrain', 'Commercial Sédentaire',
        'Responsable Commercial', 'Conseiller Client',
        'Chargé de Clientèle', 'Téléconseiller',
        'Vendeur', 'Vendeuse', 'Caissier', 'Caissière',
        'Réceptionniste', 'Agent d’Accueil',
    ],

    'title_keywords' => [
        'declarant', 'déclarant', 'douane', 'dedouanement', 'dédouanement',
        'transit', 'transitaire', 'import', 'export', 'logistique',
        'stock', 'magasinier', 'cariste', 'commande', 'entrepot', 'entrepôt',
        'technicien', 'technicienne', 'maintenance', 'electricite', 'électricité',
        'electromecanique', 'électromécanique', 'production', 'qualite', 'qualité',
        'controleur', 'contrôleur', 'responsable', 'assistant', 'assistante',
        'agent', 'chef', 'comptable', 'finance', 'rh', 'recrutement',
        'paie', 'commercial', 'clientele', 'clientèle', 'vendeur', 'vendeuse',
        'receptionniste', 'réceptionniste', 'informatique', 'reseau', 'réseau',
        'developpeur', 'développeur', 'frontend', 'backend', 'full stack',
        'data', 'designer', 'infographiste',
    ],

    /*
    |--------------------------------------------------------------------------
    | Blockers
    |--------------------------------------------------------------------------
    */

    'name_blockers' => [
        'cv', 'curriculum vitae', 'profil', 'profile', 'resume', 'résumé',
        'contact', 'coordonnees', 'coordonnées', 'adresse', 'telephone',
        'téléphone', 'portable', 'mobile', 'email', 'mail', 'linkedin',
        'objectif', 'objectifs', 'a propos', 'à propos', 'summary',
        'experience', 'expérience', 'experiences', 'expériences',
        'formation', 'formations', 'education', 'éducation',
        'competence', 'compétence', 'competences', 'compétences',
        'langue', 'langues', 'projets', 'projects', 'certificat',
        'certification', 'loisirs', 'interets', 'intérêts',
        'references', 'références', 'etat civil', 'situation familiale',
        'informations personnelles', 'personal information',
        'mission', 'missions', 'taches', 'tâches', 'responsabilites',
        'responsabilités', 'mise en service', 'expedition', 'exportation',
        'societe', 'société', 'entreprise', 'company', 'group', 'groupe',
    ],

    'name_section_blockers' => [
        'experience professionnelle', 'experiences professionnelles',
        'parcours professionnel', 'formation académique', 'formation academique',
        'diplomes', 'diplômes', 'competences techniques',
        'competences informatiques', 'langues', 'centres d interet',
        'centres d’intérêt', 'missions realisees', 'missions réalisées',
        'taches realisees', 'tâches réalisées',
    ],

    'title_blockers' => [
        'mise en service', 'missions', 'missions realisees', 'missions réalisées',
        'taches realisees', 'tâches réalisées', 'responsabilites',
        'responsabilités', 'societe', 'société', 'entreprise',
        'company', 'group', 'groupe', 'formation', 'experience',
        'expérience', 'competences', 'compétences', 'profil',
    ],

    'company_words' => [
        'societe', 'société', 'ste', 'sarl', 'sa', 'sas', 'snc', 'eurl',
        'holding', 'company', 'entreprise', 'groupe', 'group', 'industrie',
        'industries', 'maroc', 'morocco', 'bureau', 'cabinet', 'agence',
        'factory', 'usine', 'laboratoire', 'centre', 'office', 'services',
        'service', 'international', 'logistics', 'transport', 'transit',
        'import', 'export',
    ],

    'filename_noise' => [
        'cv', 'resume', 'profil', 'profile', 'updated', 'final', 'version',
        'copy', 'copie', 'new', 'nouveau', 'nouvelle', 'pdf', 'doc', 'docx',
        'scan', 'scanned', 'document',
    ],
];